import Head from "next/head";

import Navbar from "../Navbar";

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Next Practice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/darkly/bootstrap.min.css" />
            </Head>
            <Navbar />
            <main>
                {children}
            </main>
        </>
    )
}